### PR TITLE
request to merge

### PR DESCRIPTION
**Pull request by jeromesangelee**
Hi @HugoBoss33 
Can you please review and merge my code?
List of modification is below, thanks!

- fix log display with better line feed
- check no card connection of multiple reader case
- put ECC related key type based on GP amd.e	
- reset security info after select another application
- add sleep() function
- add start_timing() and stop_timing()
- restore empty reader name check which is comment with other commit by merge mistake

### CODE REVIEW

**Comment by jeromesangelee** [comment]
Hi, just commit pygp.py to resolve the conflict between latest update.

**Review by GPContributors — APPROVED** [review]

**Review by GPContributors — APPROVED** [review]

**Review by GPContributors — APPROVED** [review]

**Review by GPContributors — APPROVED** [review]

**Review by GPContributors — APPROVED** [review]

**Review by GPContributors — CHANGES_REQUESTED** [review]
Sleep function has already be implemented with the millisecond as unit.

**Review by GPContributors — CHANGES_REQUESTED** [review]
Sorry i don"t understand this commit

**Review by GPContributors — CHANGES_REQUESTED** [review]
Sorry i don't understand this commit

**Review by GPContributors — CHANGES_REQUESTED** [review]
This function has already be implemented

**Review by GPContributors — CHANGES_REQUESTED** [review]
Sorry i don't understand this commit

**Comment by jeromesangelee** [comment]
I think it would better to provide more detail for each commit. 
Let me create a new pull request with separate commit, thanks for your patience :)

**Pull request closed without merging**
