### PR TITLE
pull request review

### PR DESCRIPTION
**Pull request by jeromesangelee**
Hello @HugoBoss33 

I uploaded some changes, can you please review below?

- modify terminal() API to check multiple readers
- add 'delete key' function
- generate raw string for load block to prevent 6985 due to wrong order list
- increase default block size from 32 to 192 for large size cap file

### CODE REVIEW

**Review by GPContributors — CHANGES_REQUESTED** [review]
In the gp_functions.py there is a mistake on log_end label. 
"delete_package" in place of "delete_key"

**Review by GPContributors — CHANGES_REQUESTED** [review]
In pygp.y you call gp.delepte_package in place of delete_key
Could you also add a comment on this function ?
Tks

**Review by GPContributors — APPROVED** [review]
Thanks for this feature

**Comment by jeromesangelee** [comment]
sorry, will correct the mistake right now.

**Review by GPContributors — COMMENTED** [review]
the self.component is an OrderedDict structure. So component should be well ordored when reading a cap file. The same order should be used when executing the getRawCode function. What do you think ?

**Comment by jeromesangelee** [comment]
yes it should be ordered structure, but when I have validated different ijc and cap files, some of cap files already have this incorrect-order during read the file and this issue happened. Let me share you the test file if you want to check.

**Comment by jeromesangelee** [comment]
With some fix for the mistake, i just created another pull request for these changes.

**Pull request closed without merging**
